version: "3.3"
services:
  julia:
    environment:
      - UPLOAD_DIR="uploads"
      - DICOMS_DIR="dicoms"
      - GENIE_PORT=8001
      - FLASK_PORT=5000
    build: ./computation
    ports: 
      - "${GENIE_PORT}:${GENIE_PORT}"
  python:
    environment:
      - UPLOAD_DIR="uploads"
      - DICOMS_DIR="dicoms"
      - GENIE_PORT=8001
      - FLASK_PORT=5000
    build: ./flaskr
    ports: 
      - "${FLASK_PORT}:${FLASK_PORT}"
