name: Pylint
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: python -m pip install -r requirements.txt
      - run: pylint -E **/*.py 
    
